# Generated by Django 2.2.3 on 2019-07-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RobotTestUseCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utter', models.CharField(max_length=60)),
                ('nowtime', models.CharField(max_length=20)),
                ('session_id', models.CharField(max_length=20)),
            ],
        ),
    ]
