# Generated by Django 2.2.3 on 2019-07-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UseCase_Model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robottestusecase',
            name='expectResults',
            field=models.CharField(default='test', max_length=60),
            preserve_default=False,
        ),
    ]
