# Generated by Django 2.2.3 on 2019-08-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UseCase_Model', '0002_robottestusecase_expectresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testreport', models.CharField(max_length=60)),
                ('create_time', models.DateTimeField()),
                ('note', models.CharField(max_length=60)),
            ],
        ),
    ]
